export interface IndustryDefinition {
  id: string;
  name: string;
  icon: string;
  sector: 'agriculture' | 'manufacturing' | 'services' | 'technology' | 'energy';
  sectorType: 'primary' | 'secondary' | 'tertiary';
  description: string;
  startupCost: number;
  monthlyFixedCosts: number;
  profitMarginRange: [number, number];
  riskLevel: 'bajo' | 'medio' | 'alto';
  employeesNeeded: number;
  pricePerUnit: number;
  productionPerEmployee: number;
  demandLevel: 'baja' | 'media' | 'alta' | 'muy alta';
  growthPotential: 'bajo' | 'medio' | 'alto';
  whatYouSell: string;
  howYouEarn: string;
  tips: string;
}

export const SECTOR_TYPES = [
  {
    id: 'primary' as const,
    name: 'Sector Primario',
    subtitle: 'Extracción de recursos naturales',
    description: 'Actividades que extraen materias primas directamente de la naturaleza. Son la base de toda economía.',
    icon: '🌍',
  },
  {
    id: 'secondary' as const,
    name: 'Sector Secundario',
    subtitle: 'Transformación y manufactura',
    description: 'Transforman las materias primas en productos terminados. Agregan valor mediante trabajo y tecnología.',
    icon: '🏭',
  },
  {
    id: 'tertiary' as const,
    name: 'Sector Terciario',
    subtitle: 'Servicios y comercio',
    description: 'No producen bienes físicos — ofrecen servicios y conocimiento. Es el sector más grande en economías modernas.',
    icon: '🏪',
  },
];

export const INDUSTRIES: IndustryDefinition[] = [
  // ─── SECTOR PRIMARIO ────────────────────────────
  {
    id: 'farm',
    name: 'Granja Agrícola',
    icon: '🌾',
    sector: 'agriculture',
    sectorType: 'primary',
    description: 'Cultiva y cosecha alimentos. La demanda nunca desaparece — la gente siempre necesita comer.',
    startupCost: 5000,
    monthlyFixedCosts: 800,
    profitMarginRange: [0.10, 0.25],
    riskLevel: 'bajo',
    employeesNeeded: 3,
    pricePerUnit: 8,
    productionPerEmployee: 50,
    demandLevel: 'muy alta',
    growthPotential: 'medio',
    whatYouSell: 'Alimentos (trigo, maíz, verduras)',
    howYouEarn: 'Vendes tu cosecha a consumidores y a fábricas de alimentos. Precio estable pero márgenes bajos.',
    tips: 'Negocio seguro con demanda garantizada. Ideal para empezar. Los márgenes son bajos pero constantes.',
  },
  {
    id: 'ranch',
    name: 'Ganadería',
    icon: '🐄',
    sector: 'agriculture',
    sectorType: 'primary',
    description: 'Cría ganado para carne, leche y cuero. Mayor inversión inicial pero mejores márgenes.',
    startupCost: 12000,
    monthlyFixedCosts: 1500,
    profitMarginRange: [0.15, 0.30],
    riskLevel: 'medio',
    employeesNeeded: 4,
    pricePerUnit: 25,
    productionPerEmployee: 20,
    demandLevel: 'alta',
    growthPotential: 'medio',
    whatYouSell: 'Carne, leche, cuero',
    howYouEarn: 'Vendes productos animales. El precio fluctúa con la demanda y el costo del alimento animal.',
    tips: 'Más rentable que la granja pero necesitas más capital. El cuero lo puedes vender a fábricas textiles.',
  },
  {
    id: 'mine',
    name: 'Minería',
    icon: '⛏️',
    sector: 'energy',
    sectorType: 'primary',
    description: 'Extrae minerales y metales del subsuelo. Alta inversión, altos retornos potenciales.',
    startupCost: 30000,
    monthlyFixedCosts: 5000,
    profitMarginRange: [0.20, 0.50],
    riskLevel: 'alto',
    employeesNeeded: 8,
    pricePerUnit: 60,
    productionPerEmployee: 10,
    demandLevel: 'media',
    growthPotential: 'alto',
    whatYouSell: 'Minerales, metales, oro',
    howYouEarn: 'Vendes materias primas a fábricas. El precio depende del mercado global y la escasez.',
    tips: 'Riesgo alto: el recurso se agota. Pero si encuentras un buen yacimiento, los márgenes son enormes.',
  },
  {
    id: 'fishing',
    name: 'Pesca',
    icon: '🎣',
    sector: 'agriculture',
    sectorType: 'primary',
    description: 'Pesca y venta de productos del mar. Bajo costo inicial, depende del clima y temporada.',
    startupCost: 3000,
    monthlyFixedCosts: 500,
    profitMarginRange: [0.15, 0.35],
    riskLevel: 'medio',
    employeesNeeded: 2,
    pricePerUnit: 12,
    productionPerEmployee: 30,
    demandLevel: 'alta',
    growthPotential: 'bajo',
    whatYouSell: 'Pescado y mariscos',
    howYouEarn: 'Vendes la pesca del día. Precio variable según temporada y competencia.',
    tips: 'Fácil de empezar con poco capital. Ideal como primer negocio.',
  },
  {
    id: 'forestry',
    name: 'Silvicultura',
    icon: '🌲',
    sector: 'agriculture',
    sectorType: 'primary',
    description: 'Tala controlada y venta de madera. Recurso renovable si se gestiona bien.',
    startupCost: 8000,
    monthlyFixedCosts: 1000,
    profitMarginRange: [0.12, 0.28],
    riskLevel: 'bajo',
    employeesNeeded: 4,
    pricePerUnit: 15,
    productionPerEmployee: 25,
    demandLevel: 'media',
    growthPotential: 'medio',
    whatYouSell: 'Madera y derivados',
    howYouEarn: 'Vendes a constructoras y fábricas de muebles. Demanda estable ligada a la construcción.',
    tips: 'Negocio estable. La madera siempre se necesita para construir.',
  },

  // ─── SECTOR SECUNDARIO ──────────────────────────
  {
    id: 'food_factory',
    name: 'Fábrica de Alimentos',
    icon: '🏭',
    sector: 'manufacturing',
    sectorType: 'secondary',
    description: 'Procesa materias primas en alimentos empacados. Agrega valor a productos agrícolas.',
    startupCost: 20000,
    monthlyFixedCosts: 4000,
    profitMarginRange: [0.15, 0.35],
    riskLevel: 'medio',
    employeesNeeded: 6,
    pricePerUnit: 20,
    productionPerEmployee: 30,
    demandLevel: 'muy alta',
    growthPotential: 'alto',
    whatYouSell: 'Alimentos procesados y empacados',
    howYouEarn: 'Compras materia prima barata (granja) y vendes productos terminados más caros. La diferencia es tu ganancia.',
    tips: 'El secreto: compras trigo a $8 y vendes pan a $20. El valor agregado es donde está el dinero.',
  },
  {
    id: 'textile',
    name: 'Textil / Ropa',
    icon: '👕',
    sector: 'manufacturing',
    sectorType: 'secondary',
    description: 'Fabrica ropa y textiles. Mercado amplio pero competido.',
    startupCost: 15000,
    monthlyFixedCosts: 3000,
    profitMarginRange: [0.20, 0.45],
    riskLevel: 'medio',
    employeesNeeded: 5,
    pricePerUnit: 30,
    productionPerEmployee: 20,
    demandLevel: 'alta',
    growthPotential: 'medio',
    whatYouSell: 'Ropa y textiles',
    howYouEarn: 'Transformas tela en ropa. El margen depende de si vendes básico (bajo margen) o marca (alto margen).',
    tips: 'Puedes empezar pequeño y crecer. La clave es diferenciarte de la competencia.',
  },
  {
    id: 'construction',
    name: 'Constructora',
    icon: '🏗️',
    sector: 'manufacturing',
    sectorType: 'secondary',
    description: 'Construye edificios e infraestructura. Grandes contratos, grandes inversiones.',
    startupCost: 40000,
    monthlyFixedCosts: 8000,
    profitMarginRange: [0.10, 0.30],
    riskLevel: 'alto',
    employeesNeeded: 10,
    pricePerUnit: 100,
    productionPerEmployee: 5,
    demandLevel: 'media',
    growthPotential: 'alto',
    whatYouSell: 'Construcción de viviendas y edificios',
    howYouEarn: 'Ganas por proyecto. Compras materiales, pagas trabajadores, y cobras el proyecto terminado.',
    tips: 'Requiere mucho capital pero los contratos son grandes. Muy sensible a la tasa de interés (hipotecas).',
  },
  {
    id: 'furniture',
    name: 'Mueblería',
    icon: '🪑',
    sector: 'manufacturing',
    sectorType: 'secondary',
    description: 'Fabrica muebles con madera y materiales. Artesanía con buen margen.',
    startupCost: 10000,
    monthlyFixedCosts: 2000,
    profitMarginRange: [0.25, 0.45],
    riskLevel: 'bajo',
    employeesNeeded: 3,
    pricePerUnit: 45,
    productionPerEmployee: 10,
    demandLevel: 'media',
    growthPotential: 'medio',
    whatYouSell: 'Muebles de madera y decoración',
    howYouEarn: 'Compras madera ($15) y vendes muebles ($45+). El trabajo artesanal triplica el valor.',
    tips: 'Buen negocio para empezar. Puedes comprar madera de la silvicultura local.',
  },

  // ─── SECTOR TERCIARIO ───────────────────────────
  {
    id: 'restaurant',
    name: 'Restaurante',
    icon: '🍽️',
    sector: 'services',
    sectorType: 'tertiary',
    description: 'Prepara y vende comida. El negocio más clásico del mundo.',
    startupCost: 8000,
    monthlyFixedCosts: 2500,
    profitMarginRange: [0.10, 0.30],
    riskLevel: 'medio',
    employeesNeeded: 4,
    pricePerUnit: 15,
    productionPerEmployee: 40,
    demandLevel: 'muy alta',
    growthPotential: 'medio',
    whatYouSell: 'Comida preparada',
    howYouEarn: 'Compras ingredientes baratos y vendes platos caros. El valor está en la preparación y la experiencia.',
    tips: 'Demanda altísima pero competencia feroz. El margen está en controlar los costos de ingredientes.',
  },
  {
    id: 'store',
    name: 'Tienda / Comercio',
    icon: '🏪',
    sector: 'services',
    sectorType: 'tertiary',
    description: 'Compra productos al por mayor y vende al detalle. El intermediario.',
    startupCost: 6000,
    monthlyFixedCosts: 1500,
    profitMarginRange: [0.15, 0.35],
    riskLevel: 'bajo',
    employeesNeeded: 2,
    pricePerUnit: 18,
    productionPerEmployee: 50,
    demandLevel: 'alta',
    growthPotential: 'medio',
    whatYouSell: 'Productos variados al detalle',
    howYouEarn: 'Compras al por mayor (más barato) y vendes al detalle (más caro). La diferencia es tu margen.',
    tips: 'Negocio accesible. La clave es la ubicación y tener lo que la gente necesita.',
  },
  {
    id: 'transport',
    name: 'Transporte',
    icon: '🚛',
    sector: 'services',
    sectorType: 'tertiary',
    description: 'Mueve mercancías y personas. Esencial para conectar la economía.',
    startupCost: 15000,
    monthlyFixedCosts: 3000,
    profitMarginRange: [0.12, 0.28],
    riskLevel: 'medio',
    employeesNeeded: 3,
    pricePerUnit: 25,
    productionPerEmployee: 30,
    demandLevel: 'alta',
    growthPotential: 'alto',
    whatYouSell: 'Servicio de transporte y logística',
    howYouEarn: 'Cobras por llevar productos de A a B. Más actividad económica = más demanda de transporte.',
    tips: 'Crece con la economía. Cuando hay boom económico, el transporte explota en demanda.',
  },
  {
    id: 'health',
    name: 'Clínica / Salud',
    icon: '🏥',
    sector: 'services',
    sectorType: 'tertiary',
    description: 'Servicios médicos. Demanda inelástica — la gente siempre se enferma.',
    startupCost: 25000,
    monthlyFixedCosts: 6000,
    profitMarginRange: [0.20, 0.45],
    riskLevel: 'bajo',
    employeesNeeded: 5,
    pricePerUnit: 50,
    productionPerEmployee: 15,
    demandLevel: 'alta',
    growthPotential: 'alto',
    whatYouSell: 'Consultas médicas y tratamientos',
    howYouEarn: 'Cobras por consulta y tratamiento. La demanda no baja ni en crisis — la gente siempre necesita salud.',
    tips: 'Alto costo inicial pero negocio muy estable. La demanda es "inelástica" — no depende de la economía.',
  },
  {
    id: 'education',
    name: 'Academia / Educación',
    icon: '📚',
    sector: 'services',
    sectorType: 'tertiary',
    description: 'Enseñanza y capacitación. Inversión en capital humano.',
    startupCost: 5000,
    monthlyFixedCosts: 1200,
    profitMarginRange: [0.25, 0.50],
    riskLevel: 'bajo',
    employeesNeeded: 2,
    pricePerUnit: 20,
    productionPerEmployee: 25,
    demandLevel: 'media',
    growthPotential: 'alto',
    whatYouSell: 'Cursos, talleres, capacitación',
    howYouEarn: 'Cobras por alumno. El costo de enseñar a 1 o a 20 es casi el mismo — alta escalabilidad.',
    tips: 'Bajo costo, alto margen. El conocimiento no se agota. Escala fácilmente.',
  },
  {
    id: 'tech_startup',
    name: 'Startup Tecnológica',
    icon: '💻',
    sector: 'technology',
    sectorType: 'tertiary',
    description: 'Crea software y soluciones digitales. El sector con mayor potencial de crecimiento.',
    startupCost: 8000,
    monthlyFixedCosts: 2000,
    profitMarginRange: [0.30, 0.70],
    riskLevel: 'alto',
    employeesNeeded: 3,
    pricePerUnit: 40,
    productionPerEmployee: 20,
    demandLevel: 'alta',
    growthPotential: 'alto',
    whatYouSell: 'Software, apps, servicios digitales',
    howYouEarn: 'Creas un producto digital una vez y lo vendes infinitas veces. Margen altísimo pero riesgo alto.',
    tips: 'El negocio más escalable: costo marginal casi cero. Pero muchos fallan antes de encontrar mercado.',
  },
  {
    id: 'consulting',
    name: 'Consultoría',
    icon: '💼',
    sector: 'services',
    sectorType: 'tertiary',
    description: 'Vendes tu conocimiento y experiencia. Casi sin inversión inicial.',
    startupCost: 1000,
    monthlyFixedCosts: 300,
    profitMarginRange: [0.50, 0.80],
    riskLevel: 'bajo',
    employeesNeeded: 1,
    pricePerUnit: 60,
    productionPerEmployee: 10,
    demandLevel: 'media',
    growthPotential: 'medio',
    whatYouSell: 'Asesoría y conocimiento especializado',
    howYouEarn: 'Cobras por hora o por proyecto. Tu costo es tu tiempo — el margen es casi todo ganancia.',
    tips: 'El negocio más barato de empezar. Solo necesitas saber algo que otros necesiten. Limitado por tus horas.',
  },
];

export function getIndustriesBySectorType(sectorType: 'primary' | 'secondary' | 'tertiary'): IndustryDefinition[] {
  return INDUSTRIES.filter(i => i.sectorType === sectorType);
}

export function getIndustryById(id: string): IndustryDefinition | undefined {
  return INDUSTRIES.find(i => i.id === id);
}
